### ISSUE TITLE
大神，请问降采样过多是不是会导致效果比较差？

### ISSUE THREAD

**Issue by zhongqiu1245** [junqiangchen/COVID-CT19-Challenge#1]
大神，我关注您的公众号很久了，您的每一篇真的都是精品，每次拜读您的文章我都受益匪浅
我有一个问题想向您请教一下：
在您的model_resNet2d.py中，我发现您用了6次降采样（而resnet总共用了4次）。请问降采样次数用的多会不会对结果有没有什么负面影响？会不会存在降采样次数较多导致最后效果较差的原因呢？
以上的想法也纯属我的个人见解，如果有不对的地方也希望您能批评指正

**Comment by junqiangchen** [comment]
> 大神，我关注您的公众号很久了，您的每一篇真的都是精品，每次拜读您的文章我都受益匪浅
> 我有一个问题想向您请教一下：
> 在您的model_resNet2d.py中，我发现您用了6次降采样（而resnet总共用了4次）。请问降采样次数用的多会不会对结果有没有什么负面影响？会不会存在降采样次数较多导致最后效果较差的原因呢？
> 以上的想法也纯属我的个人见解，如果有不对的地方也希望您能批评指正

您好，由于计算资源的问题需要采用降采样处理，这个要根据实际情况来设计网络的。
谢谢

**Comment by zhongqiu1245** [comment]
谢谢您
